/**
 * Planning and Task Decomposition Types
 *
 * Defines the contracts for intent classification, task planning,
 * and orchestration execution.
 */

/**
 * Represents a single task in a task plan
 */
export interface PlannedTask {
  /** Unique identifier for this task */
  id: string;

  /** Tag identifying the capability/task type (e.g., "jobs:enrich", "resume:tailor") */
  tag: string;

  /** Task IDs that must complete before this task can run */
  dependsOn: string[];

  /** Group of tasks that can run in parallel together */
  parallelGroup: string | null;

  /** Input context types required by this task */
  inputContextTypes: string[];

  /** Output context type produced by this task */
  outputContextType: string;

  /** Payload data for this task (optional, can come from context) */
  payload?: Record<string, unknown>;

  /** TTL for output context in hours */
  outputContextTtlHours?: number;

  /** Priority within the parallel group (lower = higher priority) */
  priority?: number;

  /** Description of what this task does (for debugging/logging) */
  description?: string;
}

/**
 * Aggregation strategy for combining results
 */
export type AggregationStrategy = "merge" | "rank" | "vote" | "chain" | "pass_through";

/**
 * A complete task plan generated by the planner
 */
export interface TaskPlan {
  /** Unique identifier for this plan */
  id: string;

  /** Original user request text */
  originalRequest: string;

  /** Intent tags identified from the request */
  intents: IntentClassification[];

  /** Ordered/structured list of tasks to execute */
  tasks: PlannedTask[];

  /** How to aggregate results from all tasks */
  aggregationStrategy: AggregationStrategy;

  /** Whether tasks should be executed sequentially or in dependency order */
  executionMode: "sequential" | "dependency_aware";

  /** Any metadata about the planning process */
  metadata?: {
    /** Confidence score for the overall plan (0-1) */
    confidence?: number;
    /** Estimated total steps */
    estimatedSteps?: number;
    /** Reasoning for the plan structure */
    reasoning?: string;
  };
}

/**
 * Intent classification result
 */
export interface IntentClassification {
  /** Intent tag (e.g., "jobs:research", "resume:tailor") */
  tag: string;

  /** Confidence score (0-1) */
  confidence: number;

  /** Reasoning for this classification */
  reason?: string;
}

/**
 * Task execution result
 */
export interface TaskExecutionResult {
  taskId: string;
  tag: string;
  status: "success" | "failed" | "skipped";
  output?: unknown;
  outputContextId?: string;
  error?: string;
  durationMs: number;
  executedAt: string;
}

/**
 * Aggregation input combining all task results
 */
export interface AggregationInput {
  /** The original task plan */
  plan: TaskPlan;

  /** All task execution results */
  results: TaskExecutionResult[];

  /** Map of context IDs to their contents */
  contextContents: Map<string, unknown>;
}

/**
 * Aggregation output after processing
 */
export interface AggregationOutput {
  /** Final combined output */
  content: unknown;

  /** Strategy that was used */
  strategy: AggregationStrategy;

  /** Summary of what was done */
  summary: string;

  /** Any warnings or notes */
  warnings?: string[];
}

/**
 * Rule-based intent matcher entry
 */
export interface IntentRule {
  /** Pattern to match (simple keyword or regex) */
  pattern: string;

  /** Intent tag to assign when pattern matches */
  intentTag: string;

  /** Priority (higher = checked first) */
  priority: number;

  /** Whether pattern is a regex */
  isRegex?: boolean;
}
